{
 "title": "StatusCode",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Edge 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "edge_2xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Edge 3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "edge_3xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Edge 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "edge_4xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Edge 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "edge_5xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Origin 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "origin_2xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Origin 3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "origin_3xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Origin 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "origin_4xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Origin 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "origin_5xx", "legendFormat": "__auto" }
   ]
  }
 ]
}